### ISSUE TITLE
Multi-user service does not support 2022-blake3-chacha20-poly1305

### ISSUE THREAD

**Issue by Mahdi-zarei** [SagerNet/sing-shadowsocks#10]
The implementation of the multi-user service does not support the use of 2022-blake3-chacha20-poly1305 method, and adopting this method requires significant changes in the code, which is currently out of my knowledge. It would be nice to either implement this feature or note this in the shadowsocks' docs.

**Comment by nekohasekai** [comment]
SIP023 (EIH) only works with AES ciphers, i.e. you can't make such a thing.

Reference: https://shadowsocks.org/doc/sip023.html

**Comment by Mahdi-zarei** [comment]
I wrongly assumed that it is related to the implementation. It would be great if you could elaborate on this matter in the docs for shadowsocks. Thank you in advance.
